### ISSUE TITLE
Am I doing this right? 

### ISSUE THREAD

**Issue by onticinc** [onticinc/barricade#1]
I added the extra user data in the model and am working on updating the tests. Just wondering if I am doing this correctly and if I need to update all of the the validations with the new fields? 

For example. Would I need to replicate what I did here on lines 28, 40, 52, etc... 

https://github.com/onticinc/barricade/blob/82da665d9c0029419bc1709a6a1b3e3f09100223/test/user.test.js#L11-L26

**Comment by romebell** [comment]
@onticinc Yes, you will need to replicate for the other test as well.
