### ISSUE TITLE
Not sure what my problem is... 

### ISSUE THREAD

**Issue by onticinc** [onticinc/barricade#3]
This is the error message. 

SyntaxError: Unexpected token '.' in /Users/audiostar/sites/SEI-1025/unit-2/deliverables/barricade/views/beers/show.ejs while compiling ejs

I can't find the . that it is referring to. 

https://github.com/onticinc/barricade/blob/75e2cf8b9fef5be9aaf5a07c61f38e708ba95a1d/views/beers/show.ejs#L1-L28

Thanks for your help.

**Comment by ghost** [comment]
line 24, `delete` is a keyword/operator in javascript that cannot have any members, similar to a `+` sign or the keyword `function`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete

you might want `beer.id`?

**Comment by onticinc** [comment]
Thank you!
